### PR TITLE
Fixes annoying IDE complaints

### PR DESCRIPTION
**Pull request by zfbx**
**Describe Pull request**
I know it's a few more lines but not a single extension available shuts up about this syntax style and I hate it.. so I'd like if this was merged, if it's not, then oh well but it would be really nice <3

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? maybe?

### CODE REVIEW

**Comment by zfbx** [comment]
@Mojito-Fivem It was merged JUST because you didn't like it 👍

**Comment by Mojito-Fivem** [comment]
That doesn't make any sense because I do like safe chaining

**Comment by zfbx** [comment]
The merge, not chaining

**Comment by Mojito-Fivem** [comment]
That's just aggressive

**Pull request merged**
