### PR TITLE
Polyzone and Target Conversion

### PR DESCRIPTION
**Pull request by trclassic92**
## PolyZones and DrawTextUi(Replace 3d DrawText)

# Config.UseTarget

- false = DrawTextUI

- True = qb-target

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by buntyverma69** [comment]
drawtext using qb-core dev branch ! i think you should changed to old drawtext maybe.

**Comment by BerkieBb** [comment]
> drawtext using qb-core dev branch ! i think you should changed to old drawtext maybe.

Why, it's a pretty heavy function, that's why we're getting rid of it

**Comment by milotiro95** [comment]
It's because i don't have https://github.com/BerkieBb/qb-target ?

**Comment by trclassic92** [comment]
> It's because i don't have https://github.com/BerkieBb/qb-target ?

If you dont have target then you most likely dont even have qb-core with drawtextui added 

https://github.com/qbcore-framework/qb-core/pull/525

**Comment by DannysRP** [comment]
The target option has to be changed to allow for multiple check in locations. the minZ and maxZ are 41, 42. So if someone drops another check in location it will not work it is has a different z. Like if you wanted to add a check in for lower pillbox

**Comment by trclassic92** [comment]
> The target option has to be changed to allow for multiple check in locations. the minZ and maxZ are 41, 42. So if someone drops another check in location it will not work it is has a different z. Like if you wanted to add a check in for lower pillbox

The target option did have it but I forgot to change the E section minz and maxz. Thank you for pointing that out.

**Comment by DannysRP** [comment]
Yeah sorry I know I worded it REALLY bad lol but I'm glad you understood anyways lol

**Comment by Andyauk** [comment]
> The target option has to be changed to allow for multiple check in locations. the minZ and maxZ are 41, 42. So if someone drops another check in location it will not work it is has a different z. Like if you wanted to add a check in for lower pillbox

and also for the vehicles as I use 4 places and when I take any out they take me back to outside pillbox lol,
keep up the great work.

**Comment by trclassic92** [comment]
> > The target option has to be changed to allow for multiple check in locations. the minZ and maxZ are 41, 42. So if someone drops another check in location it will not work it is has a different z. Like if you wanted to add a check in for lower pillbox
> 
> and also for the vehicles as I use 4 places and when I take any out they take me back to outside pillbox lol, keep up the great work.

I tried to recreate this issue in 4 different locations and I could not recreate it .

Here is the video of the recreation (The video only shows the drawtextui meanwhile outside of the video I also tested this with qb-target and got the same results) https://youtu.be/ExpeJjZxOrM

**Comment by Andyauk** [comment]
with the update the vehicle distance check update it will spawn the Heli wherever you are if you press E, I noticed I didn't set to false on target, so going to see if fine on target to true.

**Comment by Andyauk** [comment]
> Yesterday before I pushed the changes I never noticed this issue... You are more then welcome to send me a video of this issue occurring if you like.
> 
> Target is no longer a option for spawning vehicles and the helicopters.

I tried a few different things and I couldn't recreate it.

**Comment by Monkey1995** [comment]
Capture
im having this issue probably something im not doing correct though!

**Comment by BerkieBb** [comment]
> Capture im having this issue probably something im not doing correct though!

You need qb-core from the dev branch

**Pull request merged**
