### PR TITLE
fix: SendToBed2 Doesn't Exist / Not Needed

### LINKED ISSUE #200: [BUG] Jailbeds not working
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.
When a player is jailed and die, following the bleed out pressing E to respawn will take you to the default "beds" in the config and not the "jailbeds" as it is suppose to. I have tried several attempts at changing the code myself but arent that experienced at it. 

**To Reproduce**
1. Be jailed by a cop
2. Jump off a building or get killed
3. Finish the bleed out stage
4. Press E when able to be sent to the "beds" section rather than the "jailbeds"

**Expected behavior**
It should choose a "jailbeds" bed from the config

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] A few days ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] zdiscord, no other custom ones related
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**
it seams that the server.lua calls a function that isnt there in the client.lua

### PR DESCRIPTION
**Pull request by dennrick**
**Describe Pull request**
This event doesn't exist and is causing issue #200.  Since this is just sending to the bed and is not dependent on the config we don't need a SendToBed2 event here.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? YES
- Does your code fit the style guidelines? YES
- Does your PR fit the contribution guidelines? YES

fixes #200

### CODE REVIEW

**Review by TonybynMp4 — APPROVED** [review]

**Comment by Bigbearbeasttv** [comment]
This is for the Jail Beds and IS needed.

**Review by Bigbearbeasttv — COMMENTED** [review]
This is for the Jail Beds and IS needed or else you are sending them from jail to the hospital...

**Comment by dennrick** [comment]
> This is for the Jail Beds and IS needed or else you are sending them from jail to the hospital...

This isn't true.  We need the SetBed2 event which tells the script what bed to put them in.  The SendToBed event just handles the process of moving the player to a bed and telling the script to revive them.

**Comment by Holidayy95** [comment]
It does exist, what are you talking about lmao. It's inside and if/else statement in **hospital:server:RespawnAtHospital** event. If you are getting errors, probably because you broke something.

**Comment by Holidayy95** [comment]
Typo on my part

**Review by GhzGarage — APPROVED** [review]

**Pull request merged**
