### PR TITLE
0 Doctors

### PR DESCRIPTION
**Pull request by erikmeyer08**
Changed for if you set the config to 0 doctors.

### CODE REVIEW

**Comment by GhzGarage** [comment]
This should work just fine without needing that code?

**Comment by erikmeyer08** [comment]
> This should work just fine without needing that code?

If you set it to 0 in the config then it still sends the alert to EMS and wont check you in since its set to >=.

**Comment by FjamZoo** [comment]
yeah it's not meant to sent an alert and then allow you to check in so that config isnt supposed to happen

**Review by IdrisDose — APPROVED** [review]
You could make it larget than the number in your server so it never triggers if you want to disable but I guess 0 works as well.

**Comment by erikmeyer08** [comment]
Yeah it was just confusing. I basically just wanted to turn it off and allow people to check in no matter how many ems was on duty and not send the alert.

Anyways, thanks!

**Pull request closed without merging**
