### PR TITLE
Create fr.lua

### PR DESCRIPTION
**Pull request by TonybynMp4**
Might need a better translation for the Checks in stuff

### CODE REVIEW

**Review by Demo4889 — CHANGES_REQUESTED** [review]
If you change `check_in = '~g~E~w~ - S\'enregistrer',` to `~g~E~w~ - Enregistrement` it should be good for the translation for Check In.

**Comment by dexter9006** [comment]
I would propose check_in = '~g~E~w~ - S\'enregistrer', to "~g~E~w~ - Hospitalisation" , it should be more understood

**Review by dexter9006 — APPROVED** [review]
I would propose check_in = 'gEw - S'enregistrer', to "gEw - Hospitalisation" , it should be more understood

**Comment by TonybynMp4** [comment]
> I would propose check_in = 'gEw - S'enregistrer', to "gEw - Hospitalisation" , it should be more understood

S'hospitaliser sounds better but yeah thanks !
Now just gotta wait for the PR to go through.

**Pull request merged**
