### PR TITLE
Remove Constant loop add export

### PR DESCRIPTION
**Pull request by KamuiKody**
This removes the constant loop checking for painkillers and creates an export for it. You can now activate the painkiller loop with other resources by using
exports['qb-ambulancejob']:PainKillerLoop(amount)
amount being the amount of painkillers you are on.
I have tested this about 5-6 different ways it works beautifully
If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by LV-Soft** [comment]
Why you put the variable "pkAmount"?, It is not used anywhere in this resource.

**Comment by KamuiKody** [comment]
Thats part of the export

**Review by i-kulgu — APPROVED** [review]
It works without any errors for me.
When i use the painkiller i can see from resmon values and profiler that the loop runs when used and stops after wait time.

**Comment by LV-Soft** [comment]
my bad, I had not seen the parameter of the function

**Review by tom-osborne — APPROVED** [review]

**Pull request merged**
