### PR TITLE
Add better multiple hospital support + some refactors

### PR DESCRIPTION
**Pull request by BackSH00TER**
**Describe Pull request**
The main purpose of this PR is to tweak the existing implementations to make it easier to add support for multiple hospitals and clean up the logic surrounding this. It also cleans up a lot of the logic with regards to finding a free bed at the hospital.

- Updates `Config.Locations` to add each hospital location and its corresponding bed locations
- Combines `GetAvailableBed` and `SetClosestBed` with a newer function `getClosestAvailableBed` that takes the index of the hospital you are at to reduce the number of loops that are needed.
- Uses `hospitalIndex` to select the correct bed at that hospital location
- Updated areas that were previously looking at Config.Locations.beds to now look at Config.Locations.hospital[hospitalIndex].beds
- Updated some strings to use the correct hospital name

Tested:
- Hold E to respawn will still respawn you at Pillbox
- Checkin at hospitals will put you in the first open bed at that hospital
- Tested getting on hospital bed by walking up to and using the nearby functions to sit on bed
- Tested that beds isTaken status correctly resets when you leave the bed

Example showing checkin + sit on bed
https://clipchamp.com/watch/DL7ruUxMQpD

### CODE REVIEW

**Comment by nzkfc** [comment]
@BackSH00TER Could you please add it so it will check which hospital you're closest too and spawn you there instead of pillbox?

Also I noticed when I added a 3rd checkin location, the option is there but doesn't do anything?

**Review by TheBlokker — APPROVED** [review]

**Comment by BackSH00TER** [comment]
Commenting to remove staleness. Can someone from QB team comment whether or not this is something you would want to merge in? If yes, I'll update and fix the merge conflicts, if no, then lets just close this out

**Comment by Twikii** [comment]
> Commenting to remove staleness. Can someone from QB team comment whether or not this is something you would want to merge in? If yes, I'll update and fix the merge conflicts, if no, then lets just close this out

I have try it on my server, its working smoothly, thanks bro!

**Comment by Irishstevie** [comment]
I can say this is something that would be awesome to see

**Review by TheBlokker — APPROVED** [review]
Perfect i dont see any problem

**Comment by BackSH00TER** [comment]
> Commenting to remove staleness. Can someone from QB team comment whether or not this is something you would want to merge in? If yes, I'll update and fix the merge conflicts, if no, then lets just close this out

@GhzGarage I would appreciate if you could take a look at this if you have a chance. I'm more than happy to update and fix the merge conflicts if this is something you would actually want merged.

**Comment by nzkfc** [comment]
I'd say do the updates anyways man, did you add the hospital distance
checking too determine where too spawn?

**Review by TheBlokker — APPROVED** [review]
I checked it again, and not error, I see no problem in the code.

Is a error in testing?

**Comment by BackSH00TER** [comment]
> I'd say do the updates anyways man, did you add the hospital distance checking too determine where too spawn?

I'm not going to waste my time continually updating and fixing merge conflicts just for the PR to sit unacknowledged for another 7+ months. 

If I get the green light from somebody who is actually on the QB team and has merge permissions, then I will be more than happy to update it.

**Comment by nzkfc** [comment]
Welcome to qbcore lol

**Comment by c-drive** [comment]
+1
This commit should really be added to **master**, it fixes a litany of issues present in the current code.

**Comment by jaylac2000** [comment]
PLZ Merge !!

**Review by SinisterDevelopment — APPROVED** [review]

**Comment by SinisterDevelopment** [comment]
i have pushed this to be merged!

**Review by TheBlokker — APPROVED** [review]
ready to be merged

**Comment by GhzGarage** [comment]
@SinisterDevelopment See if you can make a new PR on this without conflicts

**Comment by jaylac2000** [comment]
@GhzGarage 

i might have a copy of it without conflicts. just gotta delete my m-Insurance integration and reset config if you want it

**Comment by BackSH00TER** [comment]
> @SinisterDevelopment See if you can make a new PR on this without conflicts
I can update this tonight

**Comment by BackSH00TER** [comment]
Merge conflicts are fixed. This is ready to go again

**Comment by BackSH00TER** [comment]
@GhzGarage @SinisterDevelopment this PR is ready to go. Please approve so this PR can be merged. Thank you.

**Pull request merged**
