### PR TITLE
Possible fix for issue #166 and updates locale en.lua

### PR DESCRIPTION
**Pull request by OMikkel**
**Describe Pull request**
This pull request fixes a typo made, this variable was not referenced elsewhere however it should have been. 
This typo came to my attention when I was looking at the #166 issue, maybe this has something to do with the issue.
I am unsure whether or not this will fix issue #166 however it will at least fix the typo.

Since I was not able to replicate the issue mentioned to begin with, I can not verify if this fixes issue #166. It is however non breaking since I was able to test it without any problems occurring, I can verify that it is safe to integrate.

This PR also updates heli_button text in locale en.lua

If your PR is to fix an issue mention that issue here
This will **maybe** fix issue #166 

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **Yes**, and no problems were found 
- Does your code fit the style guidelines? **Yes**
- Does your PR fit the contribution guidelines? **Yes**

### CODE REVIEW

**Comment by erikmeyer08** [comment]
Same issue :(

**Comment by erikmeyer08** [comment]
I did notice a difference where I'm not using a stock helicopter where as you are.

**Comment by erikmeyer08** [comment]
Same issue even with the stock heli

image

**Comment by OMikkel** [comment]
Have you tried cloning the latest version of main branch?
It’s weird i dont experience the error

**Comment by erikmeyer08** [comment]
OK so I'm and idiot and open and close brackets make a difference in your if statements.
Sorry to waste everyone's time!

What I had: `if isPointInside and PlayerJob.name =="ambulance" or PlayerJob.name =="fire" and onDuty then`
Changed to: `if isPointInside and (PlayerJob.name =="ambulance" or PlayerJob.name =="fire") and onDuty then`

**Comment by OMikkel** [comment]
Even though the original issue #166 has been solved, I still believe it is relevant to merge this PR into main.

**Pull request merged**
